---
# Taller 1 - NumPy - Solucionario
---

1. Create a 10x10 array of zeros with the int datatype. Using slicing, assign the value 1 to the outermost elements of the array.

In [4]:
import numpy as np

In [6]:
unos = np.ones([10,10], dtype='int32')
ceros = np.zeros([8,8], dtype='int32')
#print(unos)
#print(ceros)
unos[1:-1,1:-1] = ceros
print(unos)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


2. Create a new 10x10 array of zeros. Using slicing, create a checkerboard pattern of zeros and ones.

In [ ]:
z = np.zeros([10,10], dtype='int8')
z[0:10:2,1:10:2] = 1
z[1:10:2,0:10:2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]], dtype=int8)

3. Create a 3x3x3 array of random numbers. Using boolean indexing, return, in a one dimensional array, only the numbers that are greater than 0.

In [ ]:
matriz_aleatoria = np.random.randint(-10,high=10, size=[3,3,3])
print(matriz_aleatoria)
matriz_verdadero_falso = matriz_aleatoria > 0
print(matriz_aleatoria[matriz_verdadero_falso])

[[[ -1   8   6]
  [  4 -10 -10]
  [  2   5  -1]]

 [[ -9   3   2]
  [ -4  -9  -7]
  [  8  -5   1]]

 [[  1   4   3]
  [  9   0   3]
  [  5  -5   2]]]
[8 6 4 2 5 3 2 8 1 1 4 3 9 3 5 2]


4. Create a new 10x10 array of random numbers. Using the NumPy min and max functions, calculate and print the mathematical range of the entire array (the result should only be one number, not an array).

In [24]:
matriz_aleatoria_4 = np.random.randint(0,100,size=[10,10])
maximo = matriz_aleatoria_4.max()
minimo = matriz_aleatoria_4.min()
maximo - minimo

99

5. Using the 10x10 array in the previous question, print the mathematical ranges for each row (do not output the array returned as a whole, print each element of the array).

In [29]:
matriz_aleatoria_4.max(axis=1) - matriz_aleatoria_4.min(axis=1)

array([88, 88, 90, 77, 92, 75, 99, 88, 83, 60])

6. Create 2 one dimensional arrays of random numbers, each containing 5 elements. Compare whether each element in the first array is greater than each element in the sencond array. Based on that comparison, print messages describin if the elements in the first array are (or aren't) greather than the elements in the second.

In [30]:
a = np.random.randint(0,10, size=5)
b = np.random.randint(0,10, size=5)
comparator = a > b
print(a)
print(b)
print(comparator)
for i in range(comparator.size):
    if comparator[i]:
        print("The element at the ", i, " index of array a is greather than the element at the ", i, " index of array b.")
    else:
        print("The element at the ", i, " index of array a is not greather than the element at the ", i, " index of array b.")

[6 6 3 9 5]
[2 2 0 6 5]
[ True  True  True  True False]
The element at the  0  index of array a is greather than the element at the  0  index of array b.
The element at the  1  index of array a is greather than the element at the  1  index of array b.
The element at the  2  index of array a is greather than the element at the  2  index of array b.
The element at the  3  index of array a is greather than the element at the  3  index of array b.
The element at the  4  index of array a is not greather than the element at the  4  index of array b.


7. Create a 12x12 array of ones. Using a for loop, update the values in the array to produce an array that contains the numbers from one to 144.

In [31]:
matriz_secuencia = np.ones([12,12], dtype='int32')
tamano = matriz_secuencia.shape[0]
contador = 1
for i in range(tamano):
    for j in range(tamano):
        matriz_secuencia[i,j]=contador
        contador += 1
matriz_secuencia

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48],
       [ 49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132],
       [133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144]])

8. Create a one dimensional array with the values 2000 to 2019. Once the array has been created, convert the data type of the array to integer.

In [32]:
z = np.arange(2000.0,2020.0,dtype='int32')
z

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019])

9. Create function that accepts a Fahrenheit temperature as an argument and returns a Celsius temperature. Create a NumPy array of 10 elements containing Fahrenheit degrees (you choose the temps). Use the function to convert the array into Celsius temperature and output the result.

In [ ]:
farenheit = np.array([60,34,98,34,451,323,654,321,32,15])

celcius = (farenheit - 32) / 1.8

print(celcius)

[ 15.55555556   1.11111111  36.66666667   1.11111111 232.77777778
 161.66666667 345.55555556 160.55555556   0.          -9.44444444]


10. Create a NumPy array containing the letters of the alphabet; each letter should be its own element. Based on an input from the user and the NumPy array, display the index for each character in the string. (**Big Hint:** Use the np.where function to get the index of an element in a NumPy array based on a certain condition).

In [ ]:
alfabeto = np.array(['a','b','c','d','e','f','g','h','i',
                     'j','k','l','m','n','ñ','o','p','q',
                     'r','s','t','u','v','w','x','y','z'])
nombre = "daniel"
indices = np.array([],dtype='int32')

for i in nombre:
    indices = np.append(indices,    np.where(alfabeto == i)    )


for i in range(alfabeto[indices].size):
    print(alfabeto[indices][i], ": ", indices[i])

d :  3
a :  0
n :  13
i :  8
e :  4
l :  11
