---
# Tutorial de NumPy
---

### Cargar la librería NumPy (recordar instalarlo primero)

In [1]:
import numpy as np

### Lo básico

In [2]:
# Declaración básica de un array
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
# Declaración básica de un array n dimensiones (matriz)
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Dimensiones de la matriz
a.ndim

1

In [5]:
# Forma de la matriz
b.shape

(2, 3)

In [6]:
# Tipo de dato
a.dtype

dtype('int32')

In [7]:
# Tamaño de un solo objeto del array en bytes
a.itemsize

4

In [8]:
# Tamaño total del array en bytes
a.nbytes

12

In [9]:
# Numero de elementos del array
a.size

3

### Acceder/Cambiar elementos específicos, filas, columnas, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Acceder a un elemento específico del array [r, c]
a[1, 5]

13

In [12]:
# Acceder a una fila específica 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Acceder a una columna específica
a[:, 2]

array([ 3, 10])

In [14]:
# Recorriendo la matriz con el uso de slicing [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
# Modificando elementos específicos de la matriz con slicing
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### Ejemplo 3D

In [16]:
# Define una matriz tridimensional
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Acceder a un elemento específico de la matriz 3D
b[0,1,1]

4

In [18]:
# Reemplazar elemento específico en la matriz 3D
b[:,1,:] = [[9,9],[8,8]]

In [19]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Inicializando diferentes tipos de arrays

In [20]:
# Matriz de ceros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# Matriz de unos
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [22]:
# Matriz del mismo número
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [23]:
# Matriz del mismo número con la forma de otra matriz (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [24]:
# Matriz de numeros decimales (flotantes)
np.random.rand(4,2)

array([[0.46343861, 0.18977932],
       [0.7974382 , 0.77124081],
       [0.43890808, 0.16880756],
       [0.80756914, 0.16029697]])

In [25]:
# Matriz de numeros enteros
np.random.randint(-4,8, size=(3,3))

array([[-3,  6,  2],
       [ 3,  3, -1],
       [ 5, -2,  7]])

In [26]:
# Matriz identidad
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# Copiar una una matriz y repetirla x veces en otra
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [28]:
# Ejemplo de modificación de matrices
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Ten cuidado al copiar arrays, comparten el mismo espacio de memoria!!!

In [29]:
# Forma correcta de copiar arrays
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [30]:
# Forma incorrecta
c = np.array([1,2,3,4])
d = c
d[0]=100
print(d)
print(c)

[100   2   3   4]
[100   2   3   4]


### Matemáticas

In [31]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [32]:
a + 2

array([3, 4, 5, 6])

In [33]:
a - 2

array([-1,  0,  1,  2])

In [34]:
a * 2

array([2, 4, 6, 8])

In [35]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [36]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [37]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [38]:
# Cosenos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Para más funciones (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Álgebra lineal

In [39]:
# Producto matricial
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [40]:
# Determinante
c = np.identity(3)
np.linalg.det(c)

1.0

Documentación (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc...

### Estadística

In [41]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
# Mínimo número (Todo el array)
np.min(stats)

1

In [43]:
# Máximo número (Por filas)
np.max(stats, axis=1)

array([3, 6])

In [44]:
# Suma (por columnas)
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizando arrays

In [45]:
# Reacomodando los valores una matriz, en otra matriz con otra forma
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
# Apilando arrays verticalmente 
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
# Apilando arrays horizontalmente
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Información adicional
##### Cargar datos desde un archivo

In [48]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Enmascaramiento booleano e indexación avanzada

In [49]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])